# Generated by Django 5.1.5 on 2025-01-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='published_in',
        ),
    ]
